### ISSUE TITLE
Make slidedeck easier to browse?

### ISSUE THREAD

**Issue by maelle** [ajmcoqui/testingRCode#1]
Am about to look at your slides :smile_cat: Thanks for making your material available!

Suggestion: render them via gh-pages / put a PDF on speakerdeck, and add a link to them?

**Comment by ajmcoqui** [comment]
Good call! Give me a few days - I'll do that right after the conference (and the weather/travel!) allows.

**Comment by ajmcoqui** [comment]
Fixed; see [amanda-presentation-2019-gh.md](https://github.com/ajmcoqui/testingRCode/blob/master/amanda-presentation-2019-gh.md)
